### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#610] opened 2024-02-12 14:30 UTC
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

- Also a PR template?

**Comment by OliverSchmitz** [comment] 2024-02-20 17:02
Duplicate of #534?

**Comment by kordejong** [comment] 2024-02-20 18:54
Indeed. Closed the other one.

**Closed** 2024-06-05 12:04 UTC
Labels: 25: kind: enhancement, 05: taget: documentation, 35: medium priority, great for new contributers
